name: Scrape MLH Events and Store in MongoDB

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape-mlh-events:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install webdriver-manager  # Ensure webdriver-manager is installed

      - name: Run Scraper
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
        run: python MLHscrapper.py  # Update filename if different

      - name: Notify on Failure
        if: failure()
        run: echo "Scraper failed! Check logs in GitHub Actions."
