name: Run MLH Scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape_mlh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable chromium-chromedriver
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Chrome Version: $CHROME_VERSION"
          chromedriver --version

      - name: Run MLH Scraper
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
        run: |
          python MLHscrapper.py

      - name: Upload Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: mlh-scraper-logs
          path: logs/
