name: Run Scraper Daily

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the scraper
        run: |
          python Scrapper.py  # Change to your actual script name

      - name: Commit and push results
        run: |
          git config --global user.name "Balamurugan1196"  # Change this to your GitHub username
          git config --global user.email "balamuruganb0207@gmail.com"  # Use your GitHub email
          git add .
          git commit -m "Automated data update"
          git push
