name: Scrape Hackathons

on:
  schedule:
    - cron: "0 0 */2 * *"  # Runs every 2 days
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}  # Set this in GitHub Secrets
          MONGO_PASS: ${{ secrets.MONGO_PASS }}  # Set this in GitHub Secrets
        run: python run_all_scrapers.py  # Ensure this is your script name

      - name: Notify on Failure
        if: failure()
        run: echo "Scraper failed! Check logs."
